# Generated by Django 4.1.6 on 2023-02-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgetting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailynet",
            name="daily_date",
            field=models.DateField(unique=True),
        ),
    ]
